### ISSUE TITLE
Assign unique storage path and store files for each client.

### ISSUE THREAD

**Issue by Pilipets** [smart-online-judge/basic-online-judge#40]
Currently, we have an "upload" folder to store the uploaded files, but that won't work in the case of multiple clients.

One must modify that logic to assign a new storage path for each request as well as store that path in the respective DB row.

**Comment by gevorgyana** [comment]
BTW, this issue shows why there was a need in mentioning the fact that we first implemented the system only for single user in report # 2

**Comment by gevorgyana** [comment]
Alright, here is a small report.

MinIO, the suggested solution, works with Amazon S3 protocol. It is basically an implementation of S3 Client and Server. It also provides SDKs for Python and Go that we can use to work with the Client. 

What are the benefits of using MinIO? The only benefit is that we can move to S3 when we run out of disk space.

Next, how do we use MinIO? There are several considerations. In order to understand what could possibly be done, let's understand the underlying S3 framework first. There are 3 entities.

- Buckets 
- Objects 

Buckets are responsible for geographical displacement of the data (e.g. Korean users need a server in Korea, European -- in Ireland or Frankfurt); buckets are also protected with privacy rules. For simplicity, let's say we do not allow anybody except for us, the developers, to view/edit/upload/do anything to the bucket. Okay, from the other hand, we are planning to run a local MinIO server first, so we will not need any geodata attached to our bucket (we would need it on transitioning to Amazon S3).

So we use a single bucket with the unique permissions role, that is for us, the developers.

Next, objects are accessed by keys, in our case those keys would contain the UUID4 identifier for unique access. Objects are accessed using Golang and Python MinIO SDKs.

There are several other points to consider when using MinIO/Amazon S3, but I named the most relevant ones.

**Comment by gevorgyana** [comment]
https://github.com/minio/minio-go/issues/1418 working here.

**Comment by gevorgyana** [comment]
First milestone. On triggering the rest controller we now grow the object storage, which internally looks like this (don't mind some trash data above, see how we integrate UUIDs in storage paths)
foobar
├─ localhost
│
└─ user-files
   ├─ 1873aaac-bda2-49fe-b4e6-2fac0be6a8c9
   │  ├─ README.md
   │  └─ build.ninja
   ├─ 34776b09-096d-4932-a40d-cc2647ea9e20
   │  └─ README.md
   └─ e2007bf1-c54b-4192-a826-d2614e177d4e
      └─ README.md

**Comment by Pilipets** [comment]
The fix is available in PR https://github.com/smart-online-judge/basic-online-judge/pull/68
